### ISSUE TITLE
Support Markdown formatting

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [backmeupplz/temply#2]
I would suggest adding `Markdown` and `MarkdownV2` support to the bot and its source code. If a user wants to fall back to HTML instead or switch between Markdown versions, it should place it in user settings and as per template options.

**Comment by backmeupplz** [comment]
I don't plan on implementing it, sorry. Markdown support in the current configuration (version of the Telegraf library and the way `sendCopy` handles markdown in it) is just too much pain to work with for this project. HTML support should be good enough.
